/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OwnerDashboardRouteImport } from './routes/owner-dashboard'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderRouteImport } from './routes/order'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as BookRouteImport } from './routes/book'
import { Route as BeAPartnerRouteImport } from './routes/be-a-partner'
import { Route as AdminDashboardEditRouteImport } from './routes/admin-dashboard-edit'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as OwnerRouteRouteImport } from './routes/owner/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OwnerBookingsRouteImport } from './routes/owner/bookings'
import { Route as OwnerAddHotelRouteImport } from './routes/owner/add-hotel'
import { Route as HotelsIdRouteImport } from './routes/hotels/$id'
import { Route as BookingsIdRouteImport } from './routes/bookings.$id'
import { Route as OwnerHotelsHotelIdRouteImport } from './routes/owner/hotels.$hotelId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner-dashboard',
  path: '/owner-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BeAPartnerRoute = BeAPartnerRouteImport.update({
  id: '/be-a-partner',
  path: '/be-a-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardEditRoute = AdminDashboardEditRouteImport.update({
  id: '/admin-dashboard-edit',
  path: '/admin-dashboard-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRouteRoute = OwnerRouteRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerBookingsRoute = OwnerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const OwnerAddHotelRoute = OwnerAddHotelRouteImport.update({
  id: '/add-hotel',
  path: '/add-hotel',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const HotelsIdRoute = HotelsIdRouteImport.update({
  id: '/hotels/$id',
  path: '/hotels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerHotelsHotelIdRoute = OwnerHotelsHotelIdRouteImport.update({
  id: '/hotels/$hotelId',
  path: '/hotels/$hotelId',
  getParentRoute: () => OwnerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/owner': typeof OwnerRouteRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-dashboard-edit': typeof AdminDashboardEditRoute
  '/be-a-partner': typeof BeAPartnerRoute
  '/book': typeof BookRoute
  '/explore': typeof ExploreRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/orders': typeof OrdersRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/register': typeof RegisterRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/hotels/$id': typeof HotelsIdRoute
  '/owner/add-hotel': typeof OwnerAddHotelRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/owner/hotels/$hotelId': typeof OwnerHotelsHotelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-dashboard-edit': typeof AdminDashboardEditRoute
  '/be-a-partner': typeof BeAPartnerRoute
  '/book': typeof BookRoute
  '/explore': typeof ExploreRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/orders': typeof OrdersRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/register': typeof RegisterRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/hotels/$id': typeof HotelsIdRoute
  '/owner/add-hotel': typeof OwnerAddHotelRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/admin': typeof AdminIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/owner/hotels/$hotelId': typeof OwnerHotelsHotelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/owner': typeof OwnerRouteRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-dashboard-edit': typeof AdminDashboardEditRoute
  '/be-a-partner': typeof BeAPartnerRoute
  '/book': typeof BookRoute
  '/explore': typeof ExploreRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/orders': typeof OrdersRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/register': typeof RegisterRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/hotels/$id': typeof HotelsIdRoute
  '/owner/add-hotel': typeof OwnerAddHotelRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/owner/hotels/$hotelId': typeof OwnerHotelsHotelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/owner'
    | '/about-us'
    | '/admin-dashboard'
    | '/admin-dashboard-edit'
    | '/be-a-partner'
    | '/book'
    | '/explore'
    | '/help'
    | '/login'
    | '/order'
    | '/orders'
    | '/owner-dashboard'
    | '/register'
    | '/bookings/$id'
    | '/hotels/$id'
    | '/owner/add-hotel'
    | '/owner/bookings'
    | '/admin/'
    | '/owner/'
    | '/owner/hotels/$hotelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/admin-dashboard'
    | '/admin-dashboard-edit'
    | '/be-a-partner'
    | '/book'
    | '/explore'
    | '/help'
    | '/login'
    | '/order'
    | '/orders'
    | '/owner-dashboard'
    | '/register'
    | '/bookings/$id'
    | '/hotels/$id'
    | '/owner/add-hotel'
    | '/owner/bookings'
    | '/admin'
    | '/owner'
    | '/owner/hotels/$hotelId'
  id:
    | '__root__'
    | '/'
    | '/owner'
    | '/about-us'
    | '/admin-dashboard'
    | '/admin-dashboard-edit'
    | '/be-a-partner'
    | '/book'
    | '/explore'
    | '/help'
    | '/login'
    | '/order'
    | '/orders'
    | '/owner-dashboard'
    | '/register'
    | '/bookings/$id'
    | '/hotels/$id'
    | '/owner/add-hotel'
    | '/owner/bookings'
    | '/admin/'
    | '/owner/'
    | '/owner/hotels/$hotelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerRouteRoute: typeof OwnerRouteRouteWithChildren
  AboutUsRoute: typeof AboutUsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDashboardEditRoute: typeof AdminDashboardEditRoute
  BeAPartnerRoute: typeof BeAPartnerRoute
  BookRoute: typeof BookRoute
  ExploreRoute: typeof ExploreRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  OrderRoute: typeof OrderRoute
  OrdersRoute: typeof OrdersRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  RegisterRoute: typeof RegisterRoute
  BookingsIdRoute: typeof BookingsIdRoute
  HotelsIdRoute: typeof HotelsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-dashboard': {
      id: '/owner-dashboard'
      path: '/owner-dashboard'
      fullPath: '/owner-dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/be-a-partner': {
      id: '/be-a-partner'
      path: '/be-a-partner'
      fullPath: '/be-a-partner'
      preLoaderRoute: typeof BeAPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard-edit': {
      id: '/admin-dashboard-edit'
      path: '/admin-dashboard-edit'
      fullPath: '/admin-dashboard-edit'
      preLoaderRoute: typeof AdminDashboardEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/bookings': {
      id: '/owner/bookings'
      path: '/bookings'
      fullPath: '/owner/bookings'
      preLoaderRoute: typeof OwnerBookingsRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/owner/add-hotel': {
      id: '/owner/add-hotel'
      path: '/add-hotel'
      fullPath: '/owner/add-hotel'
      preLoaderRoute: typeof OwnerAddHotelRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/hotels/$id': {
      id: '/hotels/$id'
      path: '/hotels/$id'
      fullPath: '/hotels/$id'
      preLoaderRoute: typeof HotelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/hotels/$hotelId': {
      id: '/owner/hotels/$hotelId'
      path: '/hotels/$hotelId'
      fullPath: '/owner/hotels/$hotelId'
      preLoaderRoute: typeof OwnerHotelsHotelIdRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
  }
}

interface OwnerRouteRouteChildren {
  OwnerAddHotelRoute: typeof OwnerAddHotelRoute
  OwnerBookingsRoute: typeof OwnerBookingsRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  OwnerHotelsHotelIdRoute: typeof OwnerHotelsHotelIdRoute
}

const OwnerRouteRouteChildren: OwnerRouteRouteChildren = {
  OwnerAddHotelRoute: OwnerAddHotelRoute,
  OwnerBookingsRoute: OwnerBookingsRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  OwnerHotelsHotelIdRoute: OwnerHotelsHotelIdRoute,
}

const OwnerRouteRouteWithChildren = OwnerRouteRoute._addFileChildren(
  OwnerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerRouteRoute: OwnerRouteRouteWithChildren,
  AboutUsRoute: AboutUsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDashboardEditRoute: AdminDashboardEditRoute,
  BeAPartnerRoute: BeAPartnerRoute,
  BookRoute: BookRoute,
  ExploreRoute: ExploreRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  OrderRoute: OrderRoute,
  OrdersRoute: OrdersRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  RegisterRoute: RegisterRoute,
  BookingsIdRoute: BookingsIdRoute,
  HotelsIdRoute: HotelsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
