/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OrderRouteImport } from './routes/order'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as BookRouteImport } from './routes/book'
import { Route as BeAPartnerRouteImport } from './routes/be-a-partner'
import { Route as AdminDashboardEditRouteImport } from './routes/admin-dashboard-edit'
import { Route as AdminDashboardAddRouteImport } from './routes/admin-dashboard-add'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BeAPartnerRoute = BeAPartnerRouteImport.update({
  id: '/be-a-partner',
  path: '/be-a-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardEditRoute = AdminDashboardEditRouteImport.update({
  id: '/admin-dashboard-edit',
  path: '/admin-dashboard-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardAddRoute = AdminDashboardAddRouteImport.update({
  id: '/admin-dashboard-add',
  path: '/admin-dashboard-add',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-dashboard-add': typeof AdminDashboardAddRoute
  '/admin-dashboard-edit': typeof AdminDashboardEditRoute
  '/be-a-partner': typeof BeAPartnerRoute
  '/book': typeof BookRoute
  '/explore': typeof ExploreRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-dashboard-add': typeof AdminDashboardAddRoute
  '/admin-dashboard-edit': typeof AdminDashboardEditRoute
  '/be-a-partner': typeof BeAPartnerRoute
  '/book': typeof BookRoute
  '/explore': typeof ExploreRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-dashboard-add': typeof AdminDashboardAddRoute
  '/admin-dashboard-edit': typeof AdminDashboardEditRoute
  '/be-a-partner': typeof BeAPartnerRoute
  '/book': typeof BookRoute
  '/explore': typeof ExploreRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/register': typeof RegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/admin-dashboard'
    | '/admin-dashboard-add'
    | '/admin-dashboard-edit'
    | '/be-a-partner'
    | '/book'
    | '/explore'
    | '/help'
    | '/login'
    | '/order'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/admin-dashboard'
    | '/admin-dashboard-add'
    | '/admin-dashboard-edit'
    | '/be-a-partner'
    | '/book'
    | '/explore'
    | '/help'
    | '/login'
    | '/order'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/admin-dashboard'
    | '/admin-dashboard-add'
    | '/admin-dashboard-edit'
    | '/be-a-partner'
    | '/book'
    | '/explore'
    | '/help'
    | '/login'
    | '/order'
    | '/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDashboardAddRoute: typeof AdminDashboardAddRoute
  AdminDashboardEditRoute: typeof AdminDashboardEditRoute
  BeAPartnerRoute: typeof BeAPartnerRoute
  BookRoute: typeof BookRoute
  ExploreRoute: typeof ExploreRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  OrderRoute: typeof OrderRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/be-a-partner': {
      id: '/be-a-partner'
      path: '/be-a-partner'
      fullPath: '/be-a-partner'
      preLoaderRoute: typeof BeAPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard-edit': {
      id: '/admin-dashboard-edit'
      path: '/admin-dashboard-edit'
      fullPath: '/admin-dashboard-edit'
      preLoaderRoute: typeof AdminDashboardEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard-add': {
      id: '/admin-dashboard-add'
      path: '/admin-dashboard-add'
      fullPath: '/admin-dashboard-add'
      preLoaderRoute: typeof AdminDashboardAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDashboardAddRoute: AdminDashboardAddRoute,
  AdminDashboardEditRoute: AdminDashboardEditRoute,
  BeAPartnerRoute: BeAPartnerRoute,
  BookRoute: BookRoute,
  ExploreRoute: ExploreRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  OrderRoute: OrderRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
